// <auto-generated />
using System;
using API_Gobernanza_Digital.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Gobernanza_Digital.Migrations
{
    [DbContext(typeof(GobernanzaDbContext))]
    [Migration("20251110030300_ProbandoDatosAPI")]
    partial class ProbandoDatosAPI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Boleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPagoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ContribuyenteServicioId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContribuyenteServicioId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("Boletas", (string)null);
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Contribuyente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Contribuyentes", (string)null);
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.ContribuyenteServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContribuyenteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("ContribuyenteId", "ServicioId")
                        .IsUnique();

                    b.ToTable("ContribuyenteServicios", (string)null);
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Estados", (string)null);
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Frecuencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MesesIntervalo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Frecuencias", (string)null);
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.PasarelaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlBaseApi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("PasarelasDePago", (string)null);
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Periodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<bool>("Generadas")
                        .HasColumnType("bit");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoFiscal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoFiscal")
                        .IsUnique();

                    b.ToTable("Periodos", (string)null);
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FrecuenciaId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FrecuenciaId");

                    b.ToTable("Servicios", (string)null);
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.TipoContribuyente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposContribuyente", (string)null);
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Boleta", b =>
                {
                    b.HasOne("API_Gobernanza_Digital.Models.ContribuyenteServicio", "ContribuyenteServicio")
                        .WithMany("Boletas")
                        .HasForeignKey("ContribuyenteServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Gobernanza_Digital.Models.Estado", "Estado")
                        .WithMany("Boletas")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Gobernanza_Digital.Models.Periodo", "Periodo")
                        .WithMany("Boletas")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContribuyenteServicio");

                    b.Navigation("Estado");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Contribuyente", b =>
                {
                    b.HasOne("API_Gobernanza_Digital.Models.TipoContribuyente", "Tipo")
                        .WithMany("Contribuyentes")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.ContribuyenteServicio", b =>
                {
                    b.HasOne("API_Gobernanza_Digital.Models.Contribuyente", "Contribuyente")
                        .WithMany("ContribuyenteServicios")
                        .HasForeignKey("ContribuyenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Gobernanza_Digital.Models.Servicio", "Servicio")
                        .WithMany("ContribuyenteServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribuyente");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Servicio", b =>
                {
                    b.HasOne("API_Gobernanza_Digital.Models.Frecuencia", "Frecuencia")
                        .WithMany("Servicios")
                        .HasForeignKey("FrecuenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frecuencia");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Contribuyente", b =>
                {
                    b.Navigation("ContribuyenteServicios");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.ContribuyenteServicio", b =>
                {
                    b.Navigation("Boletas");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Estado", b =>
                {
                    b.Navigation("Boletas");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Frecuencia", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Periodo", b =>
                {
                    b.Navigation("Boletas");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.Servicio", b =>
                {
                    b.Navigation("ContribuyenteServicios");
                });

            modelBuilder.Entity("API_Gobernanza_Digital.Models.TipoContribuyente", b =>
                {
                    b.Navigation("Contribuyentes");
                });
#pragma warning restore 612, 618
        }
    }
}
